version: '3'

services:
  php:
    build:
      context: ./docker/php
    volumes:
      - .:/var/www
    environment:
      PHP_IDE_CONFIG: serverName=app
      XDEBUG_MODE: develop,debug,coverage

  mysql:
    image: mysql:8.1
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_RANDOM_ROOT_PASSWORD: 1
